version: '3.9'

x-env: &env
  RAILS_ENV: development
  REDIS_URL: redis://redis:6379/1

services:
  open-food-facts-api:
    build:
      context: .
      dockerfile: Dockerfile
    command:  bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      <<: *env
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    ports:
      - "3000:3000"
    depends_on:
    - redis

  redis:
    image: redis:latest
    ports:
      - "6382:6379"

  sidekiq:
    depends_on:
      - 'open-food-facts-api'
      - 'redis'
    build:
      context: .
      dockerfile: Dockerfile
    command: sidekiq -q default
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    environment:
      <<: *env

volumes:
  gem_cache:
  db_data: