---
openapi: 3.0.1
info:
  title: Open Food Facts API - Pedro Paião
  version: v1
paths:
  "/products":
    get:
      summary: list products
      responses:
        '200':
          description: successful
servers:
- url: http://localhost:3000
  description: Local url
