development:
  clients:
    default:
      uri: "<%= Rails.application.credentials.mongodb['url'] %>"
      options:
        server_selection_timeout: 1

test:
  clients:
    default:
      uri: "<%= Rails.application.credentials.mongodb['url'] %>"
      options:
        server_selection_timeout: 1