development:
  clients:
    default:
      uri: "<%= Rails.application.credentials.mongodb['url'] %>"
      options:
        server_selection_timeout: 1
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      uri: "<%= Rails.application.credentials.mongodb['test_url'] %>"
      options:
        server_selection_timeout: 1
  options:
    raise_not_found_error: false